[project]
name = "forbidden-memories-player"
version = "0.1.0"
description = "Player to hack forbidden memories"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mss>=9.0.0",
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
    "Pillow>=10.0.0"
]
